# Generated by Django 6.0.3 on 2026-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_reconcile_existing_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrecord',
            name='label',
            field=models.CharField(default='Independent', max_length=200),
        ),
    ]
